# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'config.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Config(object):
    def setupUi(self, Config):
        Config.setObjectName("Config")
        Config.resize(509, 699)
        self.formLayoutWidget = QtWidgets.QWidget(Config)
        self.formLayoutWidget.setGeometry(QtCore.QRect(40, 30, 441, 301))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayoutRC = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayoutRC.setObjectName("formLayoutRC")
        self.labelModelId = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelModelId.setObjectName("labelModelId")
        self.formLayoutRC.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelModelId)
        self.LeModelId = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.LeModelId.setObjectName("LeModelId")
        self.formLayoutRC.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.LeModelId)
        self.labelSerialDev = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelSerialDev.setObjectName("labelSerialDev")
        self.formLayoutRC.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelSerialDev)
        self.LeDevSerial = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.LeDevSerial.setMaxLength(512)
        self.LeDevSerial.setObjectName("LeDevSerial")
        self.formLayoutRC.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.LeDevSerial)
        self.labelSpeedSerial = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelSpeedSerial.setObjectName("labelSpeedSerial")
        self.formLayoutRC.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelSpeedSerial)
        self.CbSpeedSerial = QtWidgets.QComboBox(self.formLayoutWidget)
        self.CbSpeedSerial.setObjectName("CbSpeedSerial")
        self.CbSpeedSerial.addItem("")
        self.CbSpeedSerial.addItem("")
        self.CbSpeedSerial.addItem("")
        self.CbSpeedSerial.addItem("")
        self.CbSpeedSerial.addItem("")
        self.CbSpeedSerial.addItem("")
        self.CbSpeedSerial.addItem("")
        self.CbSpeedSerial.addItem("")
        self.formLayoutRC.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.CbSpeedSerial)
        self.labelRcExePath = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelRcExePath.setObjectName("labelRcExePath")
        self.formLayoutRC.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelRcExePath)
        self.LeRcExePath = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.LeRcExePath.setMaxLength(1024)
        self.LeRcExePath.setObjectName("LeRcExePath")
        self.formLayoutRC.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.LeRcExePath)
        self.labelRcStartup = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelRcStartup.setObjectName("labelRcStartup")
        self.formLayoutRC.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.labelRcStartup)
        self.ChboxRcStartup = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.ChboxRcStartup.setObjectName("ChboxRcStartup")
        self.formLayoutRC.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.ChboxRcStartup)
        self.labelRcPoll = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelRcPoll.setObjectName("labelRcPoll")
        self.formLayoutRC.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.labelRcPoll)
        self.LeRcPollRate = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.LeRcPollRate.setInputMethodHints(QtCore.Qt.ImhNone)
        self.LeRcPollRate.setInputMask("")
        self.LeRcPollRate.setMaxLength(5)
        self.LeRcPollRate.setObjectName("LeRcPollRate")
        self.formLayoutRC.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.LeRcPollRate)
        self.labelRcPort = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelRcPort.setObjectName("labelRcPort")
        self.formLayoutRC.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.labelRcPort)
        self.LeRcPort = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.LeRcPort.setInputMask("")
        self.LeRcPort.setMaxLength(1024)
        self.LeRcPort.setObjectName("LeRcPort")
        self.formLayoutRC.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.LeRcPort)
        self.labelFilename = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelFilename.setObjectName("labelFilename")
        self.formLayoutRC.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.labelFilename)
        self.LeFilename = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.LeFilename.setMaxLength(1024)
        self.LeFilename.setObjectName("LeFilename")
        self.formLayoutRC.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.LeFilename)
        self.labelMainTitle = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelMainTitle.setObjectName("labelMainTitle")
        self.formLayoutRC.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.labelMainTitle)
        self.LeMainTitle = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.LeMainTitle.setMaxLength(50)
        self.LeMainTitle.setObjectName("LeMainTitle")
        self.formLayoutRC.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.LeMainTitle)
        self.PteRcLog = QtWidgets.QPlainTextEdit(Config)
        self.PteRcLog.setGeometry(QtCore.QRect(40, 480, 441, 191))
        self.PteRcLog.setReadOnly(True)
        self.PteRcLog.setObjectName("PteRcLog")
        self.verticalLayoutWidget = QtWidgets.QWidget(Config)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 350, 441, 91))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.PbRcTest = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.PbRcTest.setObjectName("PbRcTest")
        self.horizontalLayout.addWidget(self.PbRcTest)
        self.PbRcStart = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.PbRcStart.setObjectName("PbRcStart")
        self.horizontalLayout.addWidget(self.PbRcStart)
        self.PbRcStop = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.PbRcStop.setObjectName("PbRcStop")
        self.horizontalLayout.addWidget(self.PbRcStop)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.PbSave = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.PbSave.setObjectName("PbSave")
        self.horizontalLayout_2.addWidget(self.PbSave)
        self.PbOpen = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.PbOpen.setObjectName("PbOpen")
        self.horizontalLayout_2.addWidget(self.PbOpen)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.verticalLayoutWidget)
        self.buttonBox.setToolTip("")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_2.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.labelLog = QtWidgets.QLabel(Config)
        self.labelLog.setGeometry(QtCore.QRect(40, 460, 111, 17))
        self.labelLog.setObjectName("labelLog")

        self.retranslateUi(Config)
        self.CbSpeedSerial.setCurrentIndex(3)
        self.buttonBox.accepted.connect(Config.accept)
        self.buttonBox.rejected.connect(Config.reject)
        self.LeModelId.editingFinished.connect(Config.LeChanged)
        self.LeDevSerial.editingFinished.connect(Config.LeChanged)
        self.LeRcExePath.editingFinished.connect(Config.LeChanged)
        self.LeRcPollRate.editingFinished.connect(Config.LeChanged)
        self.LeRcPort.editingFinished.connect(Config.LeChanged)
        self.PbSave.clicked.connect(Config.PbSave_Clicked)
        self.PbOpen.clicked.connect(Config.PbOpen_Clicked)
        self.ChboxRcStartup.stateChanged['int'].connect(Config.ChboxRcStartup_StateChange)
        self.LeFilename.editingFinished.connect(Config.LeChanged)
        self.LeMainTitle.editingFinished.connect(Config.LeChanged)
        self.PbRcTest.clicked.connect(Config.PbRcTest_Clicked)
        self.PbRcStart.clicked.connect(Config.PbRcStart_Clicked)
        self.PbRcStop.clicked.connect(Config.PbRcStop_Clicked)
        QtCore.QMetaObject.connectSlotsByName(Config)

    def retranslateUi(self, Config):
        _translate = QtCore.QCoreApplication.translate
        Config.setWindowTitle(_translate("Config", "Configuration"))
        self.labelModelId.setText(_translate("Config", "Model ID"))
        self.LeModelId.setToolTip(_translate("Config", "Rotctld Rotor Model ID"))
        self.LeModelId.setInputMask(_translate("Config", "009"))
        self.LeModelId.setPlaceholderText(_translate("Config", "603"))
        self.labelSerialDev.setText(_translate("Config", "Device (Serial)"))
        self.LeDevSerial.setToolTip(_translate("Config", "Rotctld Serial Device Path"))
        self.LeDevSerial.setPlaceholderText(_translate("Config", "/dev/ttyACM0"))
        self.labelSpeedSerial.setText(_translate("Config", "Serial Speed"))
        self.CbSpeedSerial.setToolTip(_translate("Config", "Serial Baud Rate"))
        self.CbSpeedSerial.setCurrentText(_translate("Config", "9600"))
        self.CbSpeedSerial.setItemText(0, _translate("Config", "1200"))
        self.CbSpeedSerial.setItemText(1, _translate("Config", "2400"))
        self.CbSpeedSerial.setItemText(2, _translate("Config", "4800"))
        self.CbSpeedSerial.setItemText(3, _translate("Config", "9600"))
        self.CbSpeedSerial.setItemText(4, _translate("Config", "19200"))
        self.CbSpeedSerial.setItemText(5, _translate("Config", "38400"))
        self.CbSpeedSerial.setItemText(6, _translate("Config", "57600"))
        self.CbSpeedSerial.setItemText(7, _translate("Config", "115200"))
        self.labelRcExePath.setText(_translate("Config", "Path to Rotctld"))
        self.LeRcExePath.setToolTip(_translate("Config", "Path to Rotctld Executable"))
        self.LeRcExePath.setPlaceholderText(_translate("Config", "/usr/bin/rotctld"))
        self.labelRcStartup.setText(_translate("Config", "Startup Rotctld"))
        self.ChboxRcStartup.setText(_translate("Config", "on Program Start"))
        self.labelRcPoll.setText(_translate("Config", "Poll Rate (ms)"))
        self.LeRcPollRate.setToolTip(_translate("Config", "Update Rate for Rotctl"))
        self.LeRcPollRate.setPlaceholderText(_translate("Config", "1000"))
        self.labelRcPort.setText(_translate("Config", "Rotctld Port"))
        self.LeRcPort.setToolTip(_translate("Config", "Rotctld TCP Port Number (4533 is default)"))
        self.LeRcPort.setPlaceholderText(_translate("Config", "localhost:4533"))
        self.labelFilename.setText(_translate("Config", "Config File"))
        self.LeFilename.setToolTip(_translate("Config", "Config File Path"))
        self.labelMainTitle.setText(_translate("Config", "Main Title"))
        self.LeMainTitle.setToolTip(_translate("Config", "Application Display Title"))
        self.PbRcTest.setToolTip(_translate("Config", "Test if Rotctld is running"))
        self.PbRcTest.setText(_translate("Config", "Test Config"))
        self.PbRcStart.setToolTip(_translate("Config", "Startup Rotctld daemon"))
        self.PbRcStart.setText(_translate("Config", "Start Rotctld"))
        self.PbRcStop.setToolTip(_translate("Config", "Stop running Rotctld"))
        self.PbRcStop.setText(_translate("Config", "Stop Rotctld"))
        self.PbSave.setToolTip(_translate("Config", "Save Current Settings to Config File"))
        self.PbSave.setText(_translate("Config", "Save"))
        self.PbOpen.setToolTip(_translate("Config", "Open Config file"))
        self.PbOpen.setText(_translate("Config", "Open"))
        self.labelLog.setText(_translate("Config", "Log Messages"))

